#!/bin/sh -ex

xcodebuild -project "WildlifeDensity ifort.xcodeproj" -configuration Deployment

mv build/Deployment/WildlifeDensity.app/Contents/MacOS/WildlifeDensity \
"build/WildlifeDensity ifort.build/Deployment/WildlifeDensity.build/Objects-normal/i386/"

if [ -n "$1" ]; then
    ppc_executable="$1"
else
    ppc_executable="build/WildlifeDensity gfortran.build/Deployment/WildlifeDensity.build/Objects-normal/ppc/WildlifeDensity"
    xcodebuild -project "WildlifeDensity gfortran.xcodeproj" -configuration Deployment
    mv build/Deployment/WildlifeDensity.app/Contents/MacOS/WildlifeDensity "$ppc_executable"
fi

lipo -arch i386 "build/WildlifeDensity ifort.build/Deployment/WildlifeDensity.build/Objects-normal/i386/WildlifeDensity" -arch ppc "$ppc_executable" -output build/Deployment/WildlifeDensity.app/Contents/MacOS/WildlifeDensity -create
otool -L build/Deployment/WildlifeDensity.app/Contents/MacOS/WildlifeDensity

hdiutil create -layout NONE -ov -srcdir build/Deployment -format UDBZ WiDe.dmg
